spring:
  application:
    name: "ingredient-mgmt-ms"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8888"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8082