server:
  port: 8080
spring:
  application:
    name: "histamine-food"
  profiles:
    active: "dev"

  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: never
