spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: git@github.com:PawelKwidzinski/allergy-friendly-meals-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          ignore-local-ssh-settings: true
          private-key: {OPEN_SSH_PRIVATE_KEY}

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
