INSERT INTO food_histamine_levels (compatibility, histamine, other_amines, liberator, blocker, ingredient, remarks,
                                    food_subcategory, food_category)
VALUES (2, 'L', NULL, NULL, NULL, 'egg white', 'Mast cell activating especially raw, but even cooked', 'Eggs',
        'Animal foods'),
       (0, NULL, NULL, NULL, NULL, 'egg yolk', NULL, 'Eggs', 'Animal foods'),
       (2, 'L', NULL, NULL, NULL, 'eggs, chicken egg, whole egg',
        'Yolk is compatible. Egg white is mast cell activating especially raw, but even cooked.', 'Eggs',
        'Animal foods'),
       (0, NULL, NULL, NULL, NULL, 'quail eggs', NULL, 'Eggs', 'Animal foods'),
       (0, NULL, NULL, NULL, NULL, 'quails egg', NULL, 'Eggs', 'Animal foods'),
       (2, 'H', 'A', NULL, NULL, 'blue cheeses, mold cheeses', NULL, 'Cheeses', 'Dairy products'),
       (1, 'H', 'A', NULL, NULL, 'Butter: cultured butter, mildly soured butter',
        'May contain small amounts of histamine. Usually well tolerated.', 'Butter', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'butter: sweet cream butter',
        'Sweet cream butter is the normal butter, not fermented with bacteria.', 'Butter', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'Butterkaese', NULL, 'Cheeses', 'Dairy products'),
       (1, 'H', NULL, NULL, NULL, 'buttermilk (slightly sour, starting to ferment)', 'Lactic acid fermentation', 'Milk',
        'Dairy products'),
       (2, 'H', 'A', NULL, NULL, 'cheddar cheese', NULL, 'Cheeses', 'Dairy products'),
       (2, 'H', 'A', NULL, NULL, 'cheese made from unpasteurised "raw" milk',
        'Depending on hygiene. Higher risk than for cheese made from pasteurized milk', 'Cheeses', 'Dairy products'),
       (3, 'H', 'A', NULL, NULL, 'cheese: hard cheese, all well matured cheeses', NULL, 'Cheeses', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'cream cheeses (means: very young cheeses), plain, without additives', NULL,
        'Cheeses', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'cream, sweet, without additives',
        'Tolerated if unfermented. Always check for additives. Mostly contains intolerated thickeners or stabilizers, e.g. E407, E410!',
        'Cream', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'curd cheese', NULL, 'Cheeses', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'ewes milk, sheeps milk', NULL, 'Milk', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'farmers cheese (a type of fresh cheese)', NULL, 'Cheeses', 'Dairy products'),
       (1, 'H', 'A', NULL, NULL, 'Feta cheese', NULL, 'Cheeses', 'Dairy products'),
       (2, 'H', 'A', NULL, NULL, 'Fontina cheese', NULL, 'Cheeses', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'Geheimratskaese, Geheimrats cheese', NULL, 'Cheeses', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'goats milk, goat milk', NULL, 'Milk', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'Gouda cheese (young)', 'Eat small quantities only.', 'Cheeses', 'Dairy products'),
       (2, NULL, NULL, NULL, NULL, 'Gouda cheese, old', NULL, 'Cheeses', 'Dairy products'),
       (1, 'H', 'A', NULL, NULL, 'kefir, keefir, kephir', NULL, 'Milk', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'Mascarpone cheese', NULL, 'Cheeses', 'Dairy products'),
       (1, 'H', NULL, NULL, NULL, 'milk, lactosefree',
        'Sometimes well tolerated,... sometimes slightly worse tolerated than regular milk.', 'Milk', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'milk, pasteurised',
        'Milk may be incompatible, as long as the bowel is still irritated.', 'Milk', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'milk, UHT', 'UHT = ultra-high temperature processing, ultra-heat treatment', 'Milk',
        'Dairy products'),
       (1, NULL, NULL, NULL, NULL, 'milkpowder', 'Sometimes well tolerated, sometimes not.', 'Milk', 'Dairy products'),
       (2, 'H', 'A', NULL, NULL, 'mold cheeses, mould cheeses', NULL, 'Cheeses', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'Mozzarella cheese', NULL, 'Cheeses', 'Dairy products'),
       (2, 'H', 'A', NULL, NULL, 'processed cheese', NULL, 'Cheeses', 'Dairy products'),
       (2, 'H', 'A', NULL, NULL, 'products made from unprocessed (raw) milk', NULL, 'Milk', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'quark', NULL, 'Cheeses', 'Dairy products'),
       (2, 'H', 'A', NULL, NULL, 'Raclette cheese', NULL, 'Cheeses', 'Dairy products'),
       (0, 'H!', '?', '?', '?', 'raw milk', 'Perishable due to higher bacterial count. Use only fresh.', 'Milk',
        'Dairy products'),
       (2, '?', '?', NULL, NULL, 'ready made cheese preparations (with other/further ingredients)',
        'Depending on the ingredients and freshness', 'Cheeses', 'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'Ricotta cheese', NULL, 'Cheeses', 'Dairy products'),
       (2, 'H', 'A', NULL, NULL, 'Rochefort cheese', NULL, 'Cheeses', 'Dairy products'),
       (2, 'H', 'A', NULL, NULL, 'Roquefort cheese', NULL, 'Cheeses', 'Dairy products'),
       (0, NULL, '?', NULL, NULL, 'sheeps milk, sheep milk', NULL, 'Milk', 'Dairy products'),
       (1, 'H', NULL, NULL, NULL, 'sourcream', 'Lactic acid fermentation! Slightly histamine containing', 'Cream',
        'Dairy products'),
       (0, NULL, NULL, NULL, NULL, 'whey', NULL, 'Milk', 'Dairy products'),
       (1, 'H', '?', NULL, NULL, 'yoghurt (natural yoghurt)', 'Varies by product', 'Milk', 'Dairy products'),

       (0, 'H!', NULL, NULL, NULL, 'beef (fresh)', NULL, 'Meat', 'Animal foods'),
       (0, 'H!', NULL, NULL, NULL, 'chicken', NULL, 'Meat', 'Animal foods'),
       (3, 'H', 'A', NULL, NULL, 'dried meat (any kind)', NULL, 'Meat', 'Animal foods'),
       (3, 'H', 'A', NULL, NULL, 'dry-cured ham', NULL, 'Meat', 'Animal foods'),
       (0, 'H!', NULL, NULL, NULL, 'duck', NULL, 'Meat', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'entrails', NULL, 'Meat', 'Animal foods'),
       (1, 'H', NULL, NULL, NULL, 'game', 'Mostly matured meat, but fresh wild boar is well tolerated.', 'Meat',
        'Animal foods'),
       (3, 'H', 'A', NULL, NULL, 'ham (dried, cured)', NULL, 'Meat', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'innards', NULL, 'Meat', 'Animal foods'),
       (0, NULL, NULL, NULL, NULL, 'minced meat (if eaten immediately after its production)',
        'Strongly depends on the freshness', 'Meat', 'Animal foods'),
       (2, 'H', 'A', NULL, NULL, 'minced meat (open sale or pre-packed)', 'Strongly depends on the freshness', 'Meat',
        'Animal foods'),
       (0, 'H!', NULL, NULL, NULL, 'ostrich', NULL, 'Meat', 'Animal foods'),
       (1, 'H!', NULL, NULL, NULL, 'pork (fresh and untreated)',
        'Controversial.... Mostly well tolerated but very perishable. Histamine liberator -> itching?', 'Meat',
        'Animal foods'),
       (0, 'H!', NULL, NULL, NULL, 'poultry meat', NULL, 'Meat', 'Animal foods'),
       (0, 'H!', NULL, NULL, NULL, 'quail', NULL, 'Meat', 'Animal foods'),
       (3, 'H', 'A', NULL, NULL, 'salami', NULL, 'Meat', 'Animal foods'),
       (3, 'H', NULL, NULL, NULL, 'sausages of all kinds', 'A few acceptable exceptions are possible.', 'Meat',
        'Animal foods'),
       (3, 'H', NULL, NULL, NULL, 'smoked fish (any)', NULL, 'Meat', 'Animal foods'),
       (3, 'H', NULL, NULL, NULL, 'smoked meat (any)', NULL, 'Meat', 'Animal foods'),
       (0, NULL, NULL, NULL, NULL, 'tongue (veal, beef)',
        'Check for intolerated ingredients if processed ready to eat. No smoked products.', 'Meat', 'Animal foods'),
       (0, 'H!', NULL, NULL, NULL, 'turkey', NULL, 'Meat', 'Animal foods'),
       (0, 'H!', NULL, NULL, NULL, 'veal (fresh)', NULL, 'Meat', 'Animal foods'),
       (1, 'H', NULL, NULL, NULL, 'venison', 'Mostly matured meat, but fresh wild boar is well tolerated.', 'Meat',
        'Animal foods'),
       (1, 'H', NULL, NULL, NULL, 'wild meat', 'Mostly matured meat, but fresh wild boar is well tolerated.', 'Meat',
        'Animal foods'),
       (3, 'H', 'A', NULL, NULL, 'anchovies', NULL, 'Fish', 'Animal foods'),
       (0, 'H!', 'A', NULL, NULL, 'fish (freshly caught or frozen)', 'Extremely depending on freshness and species',
        'Fish', 'Animal foods'),
       (3, 'H!', 'A', NULL, NULL, 'fish (in the shop in the cooling rack or on ice)',
        'Extremely depending on freshness and species', 'Fish', 'Animal foods'),
       (0, 'H!', NULL, NULL, NULL, 'trout (freshwater): brown trout, brook trout, rainbow trout',
        'Perishable. Rapid histamine formation.', 'Fish', 'Animal foods'),
       (3, 'H', 'A', NULL, NULL, 'tuna', NULL, 'Fish', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'bivalves (mussels, oisters, clams, scallops, ...)', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'crab', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'crawfish', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'crayfish', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'langouste', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'lobster', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'oysters', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'prawn', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'rock lobsters', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'seafood, sea food', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'shellfish', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'shrimp', NULL, 'Seafood', 'Animal foods'),
       (2, 'H!', NULL, 'L', NULL, 'spiny lobsters', NULL, 'Seafood', 'Animal foods'),

       (0, NULL, NULL, NULL, NULL, 'amaranth, Amaranthus',
        'May cause diarrhea in some cases. This entry refers to the pseudo grain called amaranth, (plant genus Amaranthus). Not to be confused with the azo dye amaranth (an artificial food coloring).',
        'Starch suppliers', 'Vegetable foods'),
       (1, '?', NULL, NULL, NULL, 'baked goods',
        'Problems are often caused by: malt, iodine, long fermentation times of yeast or sourdough, possibly also ATI grains (certain varieties with amylase-tryptase-inhibitors, undeclared)',
        'Starch suppliers', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'barley', NULL, 'Starch suppliers', 'Vegetable foods'),
       (2, '?', '?', '?', NULL, 'barley malt, malt', NULL, 'Starch suppliers', 'Vegetable foods'),
       (1, '?', NULL, NULL, NULL, 'bread',
        'Problematic ingredients: malt, iodine, long fermentation times of yeast or sourdough, possibly also ATI grains (certain varieties with amylase-tryptase-inhibitors, undeclared)',
        'Starch suppliers', 'Vegetable foods'),
       (2, NULL, '?', '?', NULL, 'buckwheat', 'Only incompatible, if not thoroughly peeled?', 'Starch suppliers',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'chestnut, sweet chestnut', NULL, 'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, '!', NULL, 'cornflakes (if no additives such as malt or folic acid)',
        'Be careful with malt, folic acid', 'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'hemp seeds (Cannabis sativa)', 'The legal non-psychoactive subspecies',
        'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'KAMUT®, Khorasan wheat',
        'Prefer old varieties (e.g. KAMUT®). Modern ATI-varieties modified by cultivation are often not well tolerated.',
        'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'Khorasan wheat or Oriental wheat (Triticum turgidum ssp. turanicum), KAMUT®',
        'Prefer old varieties (e.g. KAMUT®). Modern ATI-varieties modified by cultivation are often not well tolerated.',
        'Starch suppliers', 'Vegetable foods'),
       (2, '?', '?', '?', NULL, 'malt, barley malt', NULL, 'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'maltodextrin', NULL, 'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'millet', NULL, 'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'oats', 'Some varieties may sometimes be intolerated (flatulence).',
        'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pearl sago', NULL, 'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'potato with peel',
        'Dark place! Green points are poisonous! Possibly incompatible for those with salicylate intolerance',
        'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'potato, new, with peel',
        'Dark place! Green points are poisonous! Possibly incompatible for those with salicylate intolerance',
        'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'potato, peeled', 'Dark place! Green points are poisonous!', 'Starch suppliers',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'quinoa', 'Possibly not always well tolerated?', 'Starch suppliers',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'rice', 'After cooking, store in the fridge up to 12-24 hours max.',
        'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'rice buiscuits, rice cakes', 'Slightly worse tolerated than freshly cooked rice',
        'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'rice crispies', 'Be careful with malt, folic acid', 'Starch suppliers',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'rice noodles', 'Slightly worse tolerated than freshly cooked rice',
        'Starch suppliers', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'rye', 'Barely tolerated', 'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sago', NULL, 'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, '?', NULL, 'spelt',
        'Prefer old varieties. Modern ATI-varieties modified by cultivation are often not well tolerated.',
        'Starch suppliers', 'Vegetable foods'),
       (2, NULL, NULL, 'L', NULL, 'sunflower seeds', NULL, 'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sweet corn, maize kernels: corn on the cob, fresh / pasteurised', 'Hard to digest.',
        'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sweet corn, maize kernels: dried (maize meal, maize flour)', NULL,
        'Starch suppliers', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sweet corn, maize kernels: out of the tin',
        'Hard to digest. Possibly incompatible after long-term storage or in large quantities?', 'Starch suppliers',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sweet potato', NULL, 'Starch suppliers', 'Vegetable foods'),
       (1, '?', NULL, '?', NULL, 'wheat', 'Uneven. Mostly digestive problems like flatulence.', 'Starch suppliers',
        'Vegetable foods'),
       (2, NULL, 'A', 'L', NULL, 'wheat germ', 'Putrescine, spermine, spermidine, cadaverine', 'Starch suppliers',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'wild rice', 'Wild rice is not botanically related to rice.', 'Starch suppliers',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'yam', NULL, 'Starch suppliers', 'Vegetable foods'),

       (1, NULL, NULL, NULL, NULL, 'almond', 'Small amounts are well tolerated. May cause e.g. sleep problems.', 'Nuts',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'Brazil nut', 'Max. 1-2 nuts per day are a good source of selenium', 'Nuts',
        'Vegetable foods'),
       (1, 'A', 'L', NULL, NULL, 'cashew nut', NULL, 'Nuts', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'chufa sedge (Cyperus esculentus)',
        'Actually not a nut, but tuber (thickening of stolons)', 'Nuts', 'Vegetable foods'),
       (2, NULL, '?', NULL, NULL, 'chufa sedge (Cyperus esculentus), roasted',
        'Actually not a nut, but tuber (thickening of stolons)', 'Nuts', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'earth almond', 'Actually not a nut, but tuber (thickening of stolons)', 'Nuts',
        'Vegetable foods'),
       (1, NULL, 'L', NULL, NULL, 'hazelnut', NULL, 'Nuts', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'macadamia', NULL, 'Nuts', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'nut grass', 'Actually not a nut, but tuber (thickening of stolons)', 'Nuts',
        'Vegetable foods'),
       (3, NULL, NULL, NULL, NULL, 'nuts', 'Uneven. See individual species.', 'Nuts', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'peanuts', NULL, 'Nuts', 'Vegetable foods'),
       (1, NULL, '?', NULL, NULL, 'pine nuts', 'Several species. Maybe not all of them with the same compatibility?',
        'Nuts', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pistachio', NULL, 'Nuts', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'tiger nut sedge', 'Actually not a nut, but tuber (thickening of stolons)', 'Nuts',
        'Vegetable foods'),
       (3, 'A', 'L', NULL, NULL, 'walnut', NULL, 'Nuts', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'yellow nutsedge', 'Actually not a nut, but tuber (thickening of stolons)', 'Nuts',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'black caraway oil (Nigella sativa)', 'antiallergic', 'Fats and oils',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'canola oil', NULL, 'Fats and oils', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'coconut fat, coconut oil, copra oil', 'Very recommended', 'Fats and oils',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'fennel flower oil (Nigella sativa)', 'antiallergic', 'Fats and oils',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'margarine (check for intolerated additives)', 'Check for incompatible additives',
        'Fats and oils', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'Nigella sativa oil', 'antiallergic', 'Fats and oils', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'nutmeg flower oil (Nigella sativa)', 'antiallergic', 'Fats and oils',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'olive oil', 'Incompatible for those with salicylate intolerance', 'Fats and oils',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'palm kernel oil',
        'Should not be bought for ecological reasons. Apart from that, it is recommended.', 'Fats and oils',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'palm oil, dendê oil',
        'Should not be bought for ecological reasons. Apart from that, it is recommended.', 'Fats and oils',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pumpkin seed oil',
        'This oil is made by pressing roasted, hulled pumpkin seeds (pepitas), from a local variety of pumpkin, the Styrian oil pumpkin.',
        'Fats and oils', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'rape seed oil', NULL, 'Fats and oils', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'Roman coriander oil (Nigella sativa)', 'antiallergic', 'Fats and oils','Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'safflower oil', NULL, 'Fats and oils', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'sunflower oil', 'A single dose is no problem,... but is inflammatory in the long term.', 'Fats and oils', 'Vegetable foods'),
       (2, '?', NULL, NULL, NULL, 'walnut oil', NULL, 'Fats and oils', 'Vegetable foods'),
       (2, NULL, NULL, 'L', NULL, 'beans (pulses)','Applies to virtually all types / varieties. Some tolerated exceptions are possible in some cases.','Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'beetroot', NULL, 'Vegetables', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'bell pepper (hot)', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'bell pepper (sweet)', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'bok choi', NULL, 'Vegetables', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'borlotti beans', NULL, 'Vegetables', 'Vegetable foods'),
       (2, 'H', '?', NULL, NULL, 'brinjal', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'broccoli', NULL, 'Vegetables', 'Vegetable foods'),
       (1, NULL, NULL, 'L', NULL, 'brussels sprouts', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'cabbage, green or white', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'cabbage (excepting cauliflower and kohlrabi)', NULL, 'Vegetables',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'carrot', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'cauliflower', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'celery', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'celery cabbage (Brassica rapa subsp. pekinensis)', NULL, 'Vegetables',
        'Vegetable foods'),
       (1, NULL, NULL, '?', NULL, 'chard stalks (Beta vulgaris subsp. vulgaris)', NULL, 'Vegetables',
        'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'chickpeas', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'chicory (Cichorium intybus)', NULL, 'Vegetables', 'Vegetable foods'),
       (2, NULL, NULL, '?', NULL, 'chili pepper, red, fresh', 'Hotness is irritating', 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'corn salad, lambs lettuce (Valerianella locusta)', NULL, 'Vegetables','Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'courgette', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'cucumber', NULL, 'Vegetables', 'Vegetable foods'),
       (2, 'H', '?', NULL, NULL, 'eggplant', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'endive (Cichorium endivia)', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'fennel', NULL, 'Vegetables', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'garlic', 'In small amounts, usually well tolerated after cooking', 'Vegetables',
        'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'German turnip', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'gourds', NULL, 'Vegetables', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'green beans', 'Can be well tolerated in some cases', 'Vegetables',
        'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'green peas', NULL, 'Vegetables', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'green split peas', NULL, 'Vegetables', 'Vegetable foods'),
       (1, NULL, NULL, 'L', NULL, 'horseradish', NULL, 'Vegetables', 'Vegetable foods'),
       (2, NULL, NULL, 'L', NULL, 'kelp (large seaweeds (algae) belonging to the brown algae)',
        'e.g. as an ingredient in seasoned salt / herbal salt', 'Vegetables', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'kohlrabi', NULL, 'Vegetables', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'lentils', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'lettuce iceberg', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'lettuce: head and leaf lettuces', 'Rating applies to the plant without dressing',
        'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'marrow', NULL, 'Vegetables', 'Vegetable foods'),
       (2, '?', '?', NULL, NULL, 'olives', 'Usually fermented, sometimes with intolerated ingredients', 'Vegetables',
        'Vegetable foods'),
       (1, NULL, NULL, 'L', NULL, 'onion', 'Incompatible in large quantities', 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pak choi', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'parsnip', NULL, 'Vegetables', 'Vegetable foods'),
       (2, NULL, NULL, 'L', NULL, 'perennial wall-rocket (Diplotaxis tenuifolia)', NULL, 'Vegetables',
        'Vegetable foods'),
       (3, 'H', NULL, NULL, NULL, 'pickled cabbage', NULL, 'Vegetables', 'Vegetable foods'),
       (2, 'H', '?', NULL, NULL, 'pickled cucumber', NULL, 'Vegetables', 'Vegetable foods'),
       (2, 'H', '?', NULL, NULL, 'pickled gherkin', NULL, 'Vegetables', 'Vegetable foods'),
       (2, 'H', '?', NULL, NULL, 'pickled vegetables', NULL, 'Vegetables', 'Vegetable foods'),
       (2, NULL, NULL, 'L', NULL, 'pulses (soy, beans, peas, lentils...)', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pumpkins (various varieties)', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'radish: red radish (the tiny red round ones)', NULL, 'Vegetables',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'radish: white radish (the long white ones)', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, '?', NULL, 'red cabbage', NULL, 'Vegetables', 'Vegetable foods'),
       (3, 'H', NULL, NULL, NULL, 'sauerkraut', NULL, 'Vegetables', 'Vegetable foods'),
       (1, NULL, NULL, '?', NULL, 'Savoy cabbage', NULL, 'Vegetables', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'snow peas', NULL, 'Vegetables', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'soy (soy beans, soy flour)', NULL, 'Vegetables', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'spinach', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'squashes', NULL, 'Vegetables', 'Vegetable foods'),
       (2, 'H', '?', '?', NULL, 'stinging nettle (Urtica dioica)', NULL, 'Vegetables', 'Vegetable foods'),
       (2, 'H', NULL, 'L', NULL, 'tomato', NULL, 'Vegetables', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'turnip cabbage', NULL, 'Vegetables', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'Vicia faba, broad bean', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'white onion', 'A type of onion that has a pure white skin and a sweet, mild white flesh (not the common onion).', 'Vegetables', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'yellow split peas', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'zucchini', NULL, 'Vegetables', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'basil', NULL, 'Herbs', 'Vegetable foods'),
       (1, NULL, 'L', NULL, NULL, 'bear leek (Allium ursinum)', 'Small amounts are well tolerated.', 'Herbs','Vegetable foods'),
       (1, NULL, 'L', NULL, NULL, 'bears garlic (Allium ursinum)', 'Small amounts are well tolerated.', 'Herbs', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'blue fenugreek (Trigonella caerulea)', NULL, 'Herbs', 'Vegetable foods'),
       (1, NULL, 'L', NULL, NULL, 'broad-leaved garlic (Allium ursinum)', 'Small amounts are well tolerated.', 'Herbs',
        'Vegetable foods'),
       (1, NULL, 'L', NULL, NULL, 'buckrams (Allium ursinum)', 'Small amounts are well tolerated.', 'Herbs',
        'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'chives', 'Incompatible in large quantities', 'Herbs', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'clover (trigonella and trifolium species)',
        'For example, fenugreek, blue fenugreek', 'Herbs', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'dill', 'Small amounts usually not a problem. High salicylate content.', 'Herbs',
        'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'fenugreek (Trigonella foenum-graecum)', NULL, 'Herbs', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'mint', 'Incompatible for those with salicylate intolerance', 'Herbs',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'oregano', NULL, 'Herbs', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'parsley', NULL, 'Herbs', 'Vegetable foods'),
       (1, NULL, 'L', NULL, NULL, 'ramsons (Allium ursinum)', 'Small amounts are well tolerated.', 'Herbs',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'rosemary', NULL, 'Herbs', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sage', NULL, 'Herbs', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'savory (Satureja hortensis)', NULL, 'Herbs', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'trifolium', 'For example, fenugreek, blue fenugreek', 'Herbs', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'trigonella', 'For example, fenugreek, blue fenugreek', 'Herbs', 'Vegetable foods'),
       (1, NULL, 'L', NULL, NULL, 'wild garlic (Allium ursinum)', 'Small amounts are well tolerated.', 'Herbs',
        'Vegetable foods'),
       (1, NULL, 'L', NULL, NULL, 'wood garlic (Allium ursinum)', 'Small amounts are well tolerated.', 'Herbs',
        'Vegetable foods'),

       (0, NULL, NULL, NULL, NULL, 'acerola, acerola powder, Barbados cherry, West Indian cherry, wild crepe myrtle',
        NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'apple', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'apple: Golden Delicious', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'apricot', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL,
        'aronia, chokeberries, red chokeberry (Aronia arbutifolia), black chokeberry (Aronia melanocarpa)', NULL,
        'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'Asimina triloba', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'avocado', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'banana', 'The greener the better tolerated?', 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'Barbary fig (Opuntia ficus-indica)', 'Avoid skin contact with the spikes!',
        'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'blackberry', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'blackcurrants', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'blueberries', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'boysenberry', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'cactus pear (Opuntia ficus-indica)', 'Avoid skin contact with the spikes!',
        'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'carambola, starfruit', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'cherry', 'Controversial', 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'citrus fruits', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'cocoa butter', 'Mostly well tolerated', 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'cocoa, cocoa powder (chocolate, etc.)', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'coconut, coconut shavings, coconut milk', 'Good source of selenium', 'Fruits',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'common pawpaw of NE-USA', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'common sea-buckthorn (Hippophaë rhamnoides)', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'cowberry', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'cranberry', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'dates (dried, desiccated)', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'dog rose (Rosa canina)', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'dragon fruit, pitaya, pitahaya', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'figs (fresh or dried)', 'May be slightly laxative', 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'goji berry, Chinese wolfberry, Chinese boxthorn, Himalayan goji, Tibetan goji',
        NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'gooseberry, gooseberries', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'grapefruit', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'grapes', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'guava', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'Indian fig opuntia (Opuntia ficus-indica), Barbary fig, cactus pear, spineless cactus,
        prickly pear, tuna', 'Avoid skin contact with the spikes!', 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'jostaberry', 'This plant is a hybrid between gooseberry and blackcurrant.',
        'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'kaki', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'kiwi fruit', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'ladyfinger banana', 'The greener the better tolerated', 'Fruits',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'lemon', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'lemon peel, lemon zest', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'lime', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'lingonberry', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'loganberry', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'lychee', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'mandarin orange, mandarin, mandarine(Citrus reticulata)', NULL, 'Fruits',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'mango', 'To be debated. Is often well tolerated.', 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'melons (except watermelon)',
        'Suspected occasional histamine liberator effects (due to pollutant / pesticide exposure?)', 'Fruits',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'morello cherries', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'mulberry', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'nashi pear', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'nectarine', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'orange', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'orange peel, orange zest', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'papaya, pawpaw', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'passion fruit, passionfruit', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'paw paw', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'peach', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pear', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pear, peeled canned in sugar syrup', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'persimmon', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pineapple', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pitaya, pitahaya, dragon fruit', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'plum', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pomegranate', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'prickly pear (Opuntia ficus-indica)', 'Avoid skin contact with the spikes!',
        'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'prune', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'Prunus domestica subsp. Domestica',
        'Better tolerated than other plums. Mainly cultivated in Central Europe.', 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'purple granadilla, passionfruit', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'quince', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'raisins',
        'Only if not sulphured / without sulphite / without preservatives! High salicylate content!', 'Fruits',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'raspberry', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'redcurrants, currant', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'rhubarb', 'Controversial. Often well tolerated. Oxalic acid.', 'Fruits',
        'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'rose hip', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sallow thorn', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sharon fruit', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sour cherry', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'spineless cactus (Opuntia ficus-indica)', 'Avoid skin contact with the spikes!',
        'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'strawberry', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sugar banana', 'The greener the better tolerated', 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'tamarillo, Solanum betaceum', NULL, 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'tuna, prickly pear (Opuntia ficus-indica)', 'Avoid skin contact with the spikes!',
        'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'watermelon', 'Suspected histamine liberator effects', 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'Zwetschge (damson plum subspecies domestica)',
        'Better tolerated than other plums. Mainly cultivated in Central Europe.', 'Fruits', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'chia (Salvia hispanica)', NULL, 'Seeds', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'isabgol, psyllium seed husks',
        'Can be useful both for constipation as well as diarrhea.', 'Seeds', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'ispaghula, psyllium seed husks',
        'Can be useful both for constipation as well as diarrhea.', 'Seeds', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'psyllium seed husks (Plantago ovata)',
        'Can be useful both for constipation as well as diarrhea.', 'Seeds', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'pumpkin seeds', NULL, 'Seeds', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'sesame', 'May cause diarrhea in some cases', 'Seeds', 'Vegetable foods'),
       (3, NULL, NULL, 'L', NULL, 'brown algae, algae', 'Extremely rich in iodine', 'Mushrooms, fungi and algae',
        'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'cep', NULL, 'Mushrooms, fungi and algae', 'Vegetable foods'),
       (3, NULL, NULL, 'L', NULL, 'green algae, algae', 'Extremely rich in iodine', 'Mushrooms, fungi and algae',
        'Vegetable foods'),
       (3, NULL, NULL, 'L', NULL, 'kelp, seaweed, algae', 'Extremely rich in iodine', 'Mushrooms, fungi and algae',
        'Vegetable foods'),
       (3, NULL, NULL, 'L', NULL, 'Kombu seaweed', 'Extremely rich in iodine', 'Mushrooms, fungi and algae',
        'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'morel', NULL, 'Mushrooms, fungi and algae', 'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'mushrooms, different types', NULL, 'Mushrooms, fungi and algae', 'Vegetable foods'),
       (3, NULL, NULL, 'L', NULL, 'Nori seaweed', 'Extremely rich in iodine', 'Mushrooms, fungi and algae',
        'Vegetable foods'),
       (2, NULL, NULL, NULL, NULL, 'porcino mushroom (Boletus edulis)', NULL, 'Mushrooms, fungi and algae',
        'Vegetable foods'),
       (3, NULL, NULL, 'L', NULL, 'red algae, algae', 'Extremely rich in iodine', 'Mushrooms, fungi and algae',
        'Vegetable foods'),
       (3, NULL, NULL, 'L', NULL, 'seaweed, seaweed', 'Extremely rich in iodine', 'Mushrooms, fungi and algae',
        'Vegetable foods'),
       (3, NULL, NULL, 'L', NULL, 'seaweeds and seaweed derivatives', 'Extremely rich in iodine',
        'Mushrooms, fungi and algae', 'Vegetable foods'),
       (3, NULL, NULL, 'L', NULL, 'Wakame seaweed', 'Extremely rich in iodine', 'Mushrooms, fungi and algae',
        'Vegetable foods'),
       (1, 'A', NULL, NULL, NULL, 'white button mushroom', NULL, 'Mushrooms, fungi and algae', 'Vegetable foods'),
       (1, NULL, NULL, NULL, NULL, 'yeast (fresh, dried, in all forms)',
        'Well tolerated when produced under perfect hygienic conditions. Exceptions: baked goods with a long dough fermentation time may be intolerated. High content of glutamic acid (see glutamate).', 'Mushrooms,
        fungi and algae', 'Vegetable foods'),
       (0, NULL, NULL, NULL, NULL, 'agave nectar, agave syrup', 'High fructose content', 'Beverages', 'Beverages'),
       (1, NULL, NULL, NULL, NULL, 'artificial sweeteners', 'Sucralose is tolerated.', 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'birch sugar, xylitol, xylite, E967', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'caramel (browned sugar)', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'dextrose',
        'Glucose syrup may contain a lot of fructose, pure glucose is free from fructose.', 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'E420, sorbitol, glucitol', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'E967, xylitol, xylite, birch sugar', NULL, 'Beverages', 'Beverages'),
       (2, NULL, NULL, NULL, NULL, 'extract of malt', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'fructose (fruit sugar)', 'Too much will cause indigestion.', 'Beverages',
        'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'glucose',
        'Glucose syrup may contain a lot of fructose, pure glucose is free from fructose.', 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'honey', 'To be debated. Uneven. Naturally contains benzoic acid.', 'Beverages',
        'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'inverted sugar syrup, invert sugar syrup', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'lactose (milk sugar)', NULL, 'Beverages', 'Beverages'),
       (2, '?', NULL, NULL, NULL, 'liquorice root', NULL, 'Beverages', 'Beverages'),
       (2, NULL, NULL, NULL, NULL, 'malt extract', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'maltose, malt sugar (pure)', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'maple syrup', NULL, 'Beverages', 'Beverages'),
       (0, '?', '?', NULL, NULL, 'palm sugar', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'sorbitol, glucitol, E420', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'stevia (stevia leaves, liquid, powder)', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'sucrose', 'Nevertheless, should be used sparingly,
        not as a main nutrient.', ' Beverages ', ' Beverages '),
       (0, NULL, NULL, NULL, NULL, ' sugar (beet sugar, cane sugar)', ' Nevertheless, should be used sparingly,
        not as a main nutrient.', ' Beverages ', ' Beverages '),
       (0, NULL, NULL, NULL, NULL, ' xylitol, xylite, birch sugar, E967', NULL, 'Beverages', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'anise, aniseed', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'bay laurel, laurel', 'Small amounts are well tolerated, for larger quantities lack of
        experience.', ' Spices ', ' Spices, seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'black caraway (Nigella sativa)', 'antiallergic', 'Spices',
        'Spices, seasoning, aroma'),
       (2, NULL, NULL, NULL, NULL, 'bouillon (because of yeast extract / meat extract / glutamate)',
        'Almost always with incompatible ingredients (glutamate, yeast extract, spice/aroma/flavour/seasoning/condiment/wort (in the meaning of protein hydrolysates), meat extracts, incompatible vegetables)',
        'Spices', 'Spices,
        seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'caraway (Carum carvi)',
        'Positive effect: good for heavy meals. Caution: Not to be confused with cumin (intolerated)!', 'Spices', 'Spices,
        seasoning, aroma'),
       (0, NULL, '?', NULL, NULL, 'cilantro', 'Only small amounts are well tolerated.', 'Spices',
        'Spices, seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'cinnamon', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (0, NULL, '?', NULL, NULL, 'coriander', 'Only small amounts are well tolerated.', 'Spices',
        'Spices, seasoning, aroma'),
       (2, NULL, 'L', NULL, NULL, 'cumin (Cuminum cyminum)', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (2, NULL, 'L', NULL, NULL, 'cummin', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (2, NULL, NULL, NULL, NULL, 'curry', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (0, '?', NULL, NULL, NULL, 'distilled white vinegar', 'Low histamine,
        but not free from histamine. Use sparingly. Check for intolerated additives.', 'Spices', 'Spices, seasoning,
        aroma'),
       (0, NULL, NULL, NULL, NULL, 'fennel flower (Nigella sativa)', 'antiallergic', 'Spices',
        'Spices, seasoning, aroma'),
       (1, NULL, NULL, NULL, NULL, 'ginger', 'Small amounts are well tolerated.', 'Spices', 'Spices, seasoning, aroma'),
       (2, NULL, 'L', NULL, NULL, 'Jeera', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'juniper berries', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (2, NULL, NULL, 'L', NULL, 'mustard, mustard seeds,
        mustardseed powder', 'Seeds of the mustard plant and products thereof', 'Spices', 'Spices, seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'Nigella sativa seed', 'antiallergic', 'Spices', 'Spices, seasoning, aroma'),
       (1, NULL, NULL, NULL, NULL, 'nutmeg', 'Small amounts are well tolerated.', 'Spices', 'Spices, seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'nutmeg flower (Nigella sativa)', 'antiallergic', 'Spices',
        'Spices, seasoning, aroma'),
       (2, NULL, NULL, NULL, NULL, 'paprika, hot', 'Irritating the intestine', 'Spices', 'Spices, seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'paprika, sweet', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (2, NULL, NULL, NULL, NULL, 'pepper, black', 'Small amounts are tolerated.', 'Spices',
        'Spices, seasoning, aroma'),
       (2, NULL, NULL, NULL, NULL, 'pepper, white', 'Small amounts are tolerated.', 'Spices',
        'Spices, seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'Persian cumin (Carum carvi)',
        'Positive effect: good for heavy meals. Caution: Not to be confused with cumin (intolerated)!', 'Spices', 'Spices,
        seasoning, aroma'),
       (1, NULL, NULL, NULL, NULL, 'poppy seeds', 'Small amounts are well tolerated.', 'Spices',
        'Spices, seasoning, aroma'),
       (3, 'H', '?', NULL, NULL, 'red wine vinegar', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'Roman coriander (Nigella sativa)', 'antiallergic', 'Spices',
        'Spices, seasoning, aroma'),
       (2, NULL, NULL, NULL, NULL, 'seasoning made of hydrolysated proteins', 'Derived from vegetal protein hydrolysate,
        aroma reminiscent of meat broth. Contains glutamate, histamine and other amines.', 'Spices', 'Spices, seasoning,
        aroma'),
       (3, NULL, NULL, NULL, NULL, 'soy sauce', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (0, '?', NULL, NULL, NULL, 'spirit vinegar', 'Low histamine,
        but not free from histamine. Use sparingly. Check for intolerated additives.', 'Spices', 'Spices, seasoning,
        aroma'),
       (0, NULL, NULL, NULL, NULL, 'thyme, common thyme, German thyme,
        garden thyme (Thymus vulgaris)', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (0, NULL, NULL, NULL, NULL, 'turmeric (Curcuma longa)', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (1, '?', NULL, NULL, NULL, 'vanilla extract', 'From fermented fruits, alcoholic.', ' Spices ', ' Spices, seasoning,
        aroma'),
       (1, '?', NULL, NULL, NULL, 'vanilla, vanilla pod, vanilla powder,
        vanilla sugar',
        'Tolerated in small quantities. Fermentation! Possibly traces of sulfite? (See also additives > vanillin)',
        'Spices', 'Spices,
        seasoning, aroma'),
       (1, 'H', '?', NULL, NULL, 'vinegar: apple vinegar', 'Check for additives.', 'Spices',
        'Spices, seasoning, aroma'),
       (3, 'H', '?', NULL, NULL, 'vinegar: balsamic vinegar', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (0, '?', NULL, NULL, NULL, 'vinegar: spirit vinegar, distilled white vinegar', 'Low histamine,
        but not free from histamine. Use sparingly. Check for intolerated additives.', 'Spices', 'Spices, seasoning,
        aroma'),
       (0, '?', NULL, NULL, NULL, 'white vinegar, spirit vinegar', 'Low histamine,
        but not free from histamine. Use sparingly. Check for intolerated additives.', 'Spices', 'Spices, seasoning,
        aroma'),
       (3, 'H', '?', NULL, NULL, 'white wine vinegar', NULL, 'Spices', 'Spices, seasoning, aroma'),
       (2, NULL, NULL, 'L', NULL, 'yeast extract', 'Chemical conversion to glutamate.', 'Spices',
        'Spices, seasoning, aroma'),

       (0, NULL, NULL, NULL, NULL, 'tap water', NULL, 'Water', 'Beverages'),
       (3, 'H', 'A', 'L', 'B', 'alcohol, pure(ethanol)', NULL, 'Alcoholic', 'Beverages'),
       (3, 'H', 'A', 'L', 'B', 'alcoholic beverages', NULL, 'Alcoholic', 'Beverages'),
       (2, 'H', 'A', 'L', 'B', 'beer', NULL, 'Alcoholic', 'Beverages'),
       (2, 'H', 'A', 'L', 'B', 'brandy', NULL, 'Alcoholic', 'Beverages'),
       (3, 'H', 'A', 'L', 'B', 'champagne', NULL, 'Alcoholic', 'Beverages'),
       (2, '?', '?', 'L', 'B', 'liquor, clear(colourless)', NULL, 'Alcoholic', 'Beverages'),
       (3, 'H', 'A', 'L', 'B', 'liquor, schnapps, spirits, cloudy(not colourless)', NULL, 'Alcoholic', 'Beverages'),
       (2, 'H', 'A', 'L', 'B', 'rum', NULL, 'Alcoholic', 'Beverages'),
       (2, '?', '?', 'L', 'B', 'schnapps, clear(colourless)', NULL, 'Alcoholic', 'Beverages'),
       (3, 'H', 'A', 'L', 'B', 'sparkling wine', NULL, 'Alcoholic', 'Beverages'),
       (3, 'H', 'A', 'L', 'B', 'wine', NULL, 'Alcoholic', 'Beverages'),
       (1, NULL, '?', 'L', 'B', 'wine, histamine free (<0.1 mg/l)', 'Still contains alcohol and sulfite, like any wine.For
        cooking, it is well tolerated after the alcohol has evaporated.', 'Alcoholic', 'Beverages'),
       (3, 'H', 'A', 'L', 'B', 'wine: red wine', NULL, 'Alcoholic', 'Beverages'),
       (2, 'H', 'A', 'L', 'B', 'wine: Schilcherwein', NULL, 'Alcoholic', 'Beverages'),
       (2, 'H', 'A', 'L', 'B', 'wine: white wine', NULL, 'Alcoholic', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'chamomile tea', NULL, 'Tea, herbal infusions', 'Beverages'),
       (1, NULL, NULL, NULL, 'B', 'green tea', NULL, 'Tea, herbal infusions', 'Beverages'),
       (1, NULL, '?', NULL, NULL, 'herbal teas with medicinal herbs', 'Incompatible ingredient not yet identified', 'Tea,
        herbal infusions', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'lime blossom tea', NULL, 'Tea, herbal infusions', 'Beverages'),
       (1, NULL, NULL, NULL, 'B', 'mate tea (llex paraguariensis)', NULL, 'Tea, herbal infusions', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'peppermint tea',
        'Caution: Check the list of ingredients. Tea blends (mixtures) of Rooibos & incompatible ingredients (e.g. orange zest) are often sold as "Rooibos" as well.', 'Tea,
        herbal infusions', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'rooibos tea', NULL, 'Tea, herbal infusions', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'sage tea', NULL, 'Tea, herbal infusions', 'Beverages'),
       (1, 'H', '?', '?', NULL, 'stinging nettle herbal tea (Urtica dioica)', NULL, 'Tea, herbal infusions',
        'Beverages'),
       (2, 'H', NULL, NULL, 'B', 'tea, black tea', NULL, 'Tea, herbal infusions', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'verbena herbal tea', NULL, 'Tea, herbal infusions', 'Beverages'),
       (1, NULL, NULL, NULL, NULL, 'Coca-Cola', 'See also caffeine and carbonated', 'Drinks containing caffeine',
        'Beverages'),
       (1, NULL, NULL, NULL, NULL, 'coffee', 'Caffeine stimulates nerves and bowel, which may be mast cell activating.',
        'Drinks containing caffeine', 'Beverages'),
       (1, NULL, NULL, NULL, NULL, 'Coke', 'See also caffeine and carbonated', 'Drinks containing caffeine',
        'Beverages'),
       (1, NULL, NULL, NULL, NULL, 'Cola-drinks', 'See also caffeine and carbonated', 'Drinks containing caffeine',
        'Beverages'),
       (2, '?', 'B', NULL, NULL, 'energy drinks', 'Theobromine inhibits the DAO enzyme.', 'Drinks containing caffeine',
        'Beverages'),
       (1, NULL, NULL, NULL, NULL, 'espresso', 'Better tolerated than coffee, but caffeine still stimulates nerves and bowel,
        which may be mast cell activating.', 'Drinks containing caffeine', 'Beverages'),
       (2, NULL, NULL, NULL, NULL, 'chocolate drinks', NULL, 'Soft drinks, soda', 'Beverages'),
       (2, NULL, NULL, NULL, NULL, 'cocoa drinks', NULL, 'Soft drinks, soda', 'Beverages'),
       (0, NULL, NULL, NULL, NULL, 'elderflower cordial', NULL, 'Soft drinks, soda', 'Beverages'),
       (2, NULL, NULL, NULL, NULL, 'hot chocolate', 'Depending on the ingredients', 'Soft drinks, soda', 'Beverages'),
       (1, NULL, NULL, NULL, NULL, 'lemonade', 'Depending on the ingredients', 'Soft drinks, soda', 'Beverages'),
       (2, NULL, NULL, NULL, NULL, 'Ovaltine', 'Depending on the ingredients', 'Soft drinks, soda', 'Beverages'),
       (1, NULL, NULL, NULL, NULL, 'soda', 'soft drinks', 'Soft drinks, soda', 'Beverages'),
       (2, 'L', NULL, NULL, NULL, '2-hydroxybiphenyl, E231', NULL, 'Food additives', 'Additives'),
       (1, 'L', NULL, NULL, NULL, 'acacia gum, gum arabic, E414', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'acetate of lime, calcium acetate, E262', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'acetic acid, E260', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'Acid Red 14, E122', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'agar, agar - agar, E406', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'alginic acid, algin, alginate, E400', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'Allura Red, Food Red 17, C.I.16035, FD&C Red 40, E129', NULL, 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'alpha-tocopherol, vitamin E, E307', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'amaranth, E123',
        'This refers to the azo dye amaranth, an artificial food coloring. Not to be confused with the pseudo grain amaranth from the plant genus Amaranthus.',
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'ammonia caramel, E150c', 'Possibly not as good tolerated as E150?',
        'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'ammonium alginate, E403', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'ammonium carbonate, bakers ammonia, E503', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'ammonium citrate, triammonium citrate, E380', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'annatto, bixin, norbixin, E160b', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'ascorbic acid, E300',
        'Lowers histamine levels, but is also a weak DAO inhibitor. Good for those with MCAS, bad for those with HIT?',
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'ascorbyl palmitate, E304', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'Azorubin S, E122, Brillantcarmoisin O, E122', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'azorubine, E122', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'baking soda, bicarbonate of soda, sodium hydrogen carbonate, sodium bicarbonate',
        NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'beeswax, E901', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'benzoates, E210 - 213 ', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'benzoic acid, E210', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'betanin, Beetroot Red, E162', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'bixin, norbixin, E160b', NULL, 'Food additives', 'Additives'),
       (3, NULL, 'L', NULL, NULL,
        'Brilliant Black BN, Brilliant Black PN, Brilliant Black A, Black PN, Food Black 1, Naphthol Black, E151,
        C.I.Food Black 1, C.I.28440',
        NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'Brown FK, Kipper Brown, Chocolate Brown FK, E154, C.I.Food Brown 1', NULL,
        'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'Brown HT, Chocolate Brown HT, Food Brown 3, E155, C.I.20285', NULL,
        'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'butylated hydroxyanisole, E320', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'butylated hydroxytoluene, BHT, dibutylhydroxytoluene, E321', NULL, 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'calcium acetate, acetate of lime, calcium ethanoate, calcium diacetate, E262', NULL,
        'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'calcium alginate, E404', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'calcium ascorbate, calcium diascorbate', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'calcium benzoate, E213', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'calcium bisulfite, E227', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'calcium carbonate, limestone, E170', NULL, 'Food additives', 'Additives'),
       (1, NULL, '?', NULL, NULL, 'calcium citrate, E333', 'Often well tolerated.', 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'calcium diglutamate, E623', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'calcium lactate, E327', NULL, 'Food additives', 'Additives'),
       (2, NULL, '?', NULL, NULL, 'calcium polyphosphate, E452', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'calcium sorbate, E203', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'calcium sulfite, E226', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'caramel color, caramel coloring, E150', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'carmine, E120', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'carmoisine, E122, Food Red 3, E122', NULL, 'Food additives', 'Additives'),
       (2, '?', '?', NULL, NULL, 'carob, carob powder, carob pod meal',
        'Carob is the dried (and sometimes roasted) pod, and not the seeds.', ' Food additives ', ' Additives '),
       (2, NULL, ' L ', NULL, NULL, ' carobin, carob gum, carob bean gum, E410',
        'Thickening agent and gelling agent, extracted from the seeds of the carob tree.', 'Food additives',
        'Additives'),
       (0, NULL, 'L', NULL, NULL, 'carotene, beta - carotene, β - carotene, E160a', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'carrageenan, processed seaweed, E407, E407a', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'caustic caramel, E150a', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'caustic sulphite caramel, E150b', 'Possibly not as good tolerated as E150?',
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'cellulose ethyl ether, ethyl cellulose, ethylcellulose, E462', NULL,
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL,
        'cellulose methyl ether, methyl cellulose, methylcellulose, methylated cellulose, E461',
        'May produce laxative effects in large quantities.', 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'cellulose, E460', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'charcoal, E153', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'chlorophyll, E140', NULL, 'Food additives', 'Additives'),
       (1, NULL, NULL, NULL, NULL, 'citric acid, E330', 'To be debated. Made from mold, not from lemons.',
        ' Food additives ', ' Additives '),
       (2, NULL, ' L ', NULL, NULL, ' cochineal red A, E124', NULL, 'Food additives', 'Additives'),
       (2, NULL, 'L', NULL, NULL, 'cochineal, E120', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'copper complexes of chlorophylls and chlorophyllins, E141', NULL, 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'cream of tartar, E336', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'crimson lake, E120', NULL, 'Food additives', 'Additives'),
       (1, 'L', NULL, NULL, NULL, 'crystal gum, gum karaya, karaya gum, E416', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'curcumin, E100', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'delta-tocopherol, vitamin E, E309', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'dicalcium phosphate, dicalcium hydrogen orthophosphate, E340', NULL,
        'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'dipotassium phosphate, dipotassium hydrogen orthophosphate, E340', NULL,
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'D-isoascorbate, sodium erythorbate, erythorbic acid sodium salt, E316', NULL,
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E100, curcumin', NULL, 'Food additives', 'Additives'),
       (1, 'L', NULL, NULL, NULL, 'E101a, riboflavin - 5 - phosphate', NULL, 'Food additives', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'E102, tartrazine', NULL, 'Food additives', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'E104, quinoline yellow', NULL, 'Food additives', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'E110, sunset yellow FCF', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E1103, invertase', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E120, carmine, cochineal', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'E1201, polyvinylpyrrolidone, PVP, polyvidone, povidone', NULL, 'Food additives',
        'Additives'),
       (1, '?', NULL, NULL, NULL, 'E1202, polyvinylpolypyrrolidone', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E122, azorubine, carmoisine', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E123, amaranth',
        'This refers to the azo dye amaranth, an artificial food coloring. Not to be confused with the pseudo grain amaranth from the plant genus Amaranthus.',
        'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E124, ponceau 4R, cochineal red A', NULL, 'Food additives', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'E127, erythrosine', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E129, Allura Red, Food Red 17, C.I.16035, FD&C Red 40', NULL, 'Food additives',
        'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E131, Patent blue V', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E132, indigo carmine, indigotine', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E140, chlorophyll', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E141, copper complexes of chlorophylls and chlorophyllins', NULL, 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E150, plain caramel, caustic caramel, caramel coloring', NULL, 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E150b, sulphite - caramel', 'Possibly not as good tolerated as E150?',
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E150c, ammonia caramel', 'Possibly not as good tolerated as E150?',
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E150d, sulphite ammonia caramel', 'Possibly not as good tolerated as E150?',
        'Food additives', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'E151, Brilliant Black BN, Brilliant Black PN, Brilliant Black A, Black PN, Food Black 1,
        Naphthol Black, C.I.Food Black 1, C.I.28440', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E153, charcoal', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E154, Brown FK, Kipper Brown, Chocolate Brown FK, C.I.Food Brown 1', NULL,
        'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E155, Brown HT, Chocolate Brown HT, Food Brown 3, C.I.20285', NULL, 'Food additives',
        'Additives'),
       (0, 'L', NULL, NULL, NULL, 'E160a, carotene, beta - carotene, β - carotene', NULL, 'Food additives',
        'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E160b, bixin, norbixin, annatto', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E162, betanin, Beetroot Red', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E170, calcium carbonate, limestone', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E171, titanium dioxide, titanium(IV) oxide', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E172, iron oxides', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E173, aluminium, aluminum', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E174, silver', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E175, gold', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E180, Lithol Rubine BK', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E200, sorbic acid', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E202, potassium sorbate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E203, calcium sorbate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E220, sulfur dioxide, sulphur dioxide', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E221, sodium sulfite, sodium sulphite', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E222, sodium bisulfite, sodium hydrogen sulphite', NULL, 'Food additives',
        'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E223, sodium metabisulfite, sodium pyrosulfite', NULL, 'Food additives',
        'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E224, potassium metabisulfite, potassium pyrosulfite', NULL, 'Food additives',
        'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E226, calcium sulfite', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E227, calcium bisulfite', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E228, potassium hydrogen sulfite, potassium bisulfite', NULL, 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E230, biphenyl, diphenyl', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E231, orthophenyl phenol', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E232, sodium orthophenyl phenol', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E233, thiabendazole', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E234, nisin', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E235, natamycin, pimaricin', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E236, formic acid', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E237, sodium formate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E238, calcium formate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E239, hexamethylenetetramine', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E240, formaldehyde', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E241, guaiac resin', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E242, dimethyl dicarbonate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E243, ethyl lauroyl arginate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E249, potassium nitrite', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E250, sodium nitrite', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E251, sodium nitrate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E252, potassium nitrate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E260, acetic acid', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E261, potassium acetate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E262, sodium acetate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E263, calcium acetate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E264, ammonium acetate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E270, lactic acid', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E280, propionic acid', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E281, sodium propionate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E282, calcium propionate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E283, potassium propionate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E290, carbon dioxide', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E296, malic acid', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E297, fumaric acid', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E300, ascorbic acid', 'Lowers histamine levels,
        but is also a weak DAO inhibitor. Good for those with MCAS, bad for those with HIT?', 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E301, sodium ascorbate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E302, calcium ascorbate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E304, ascorbyl palmitate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E306, tocopherol', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E307, alpha - tocopherol', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E308, gamma - tocopherol', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E309, delta - tocopherol', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E310, propyl gallate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E311, octyl gallate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E312, dodecyl gallate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E315, erythorbic acid', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E316, sodium erythorbate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E319, tert - Butylhydroquinone', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E320, butylated hydroxyanisole', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E321, butylated hydroxytoluene', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E322, lecithins', 'Mostly soya lecithin', 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E325, sodium lactate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E326, potassium lactate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E327, calcium lactate', NULL, 'Food additives', 'Additives'),
       (1, NULL, NULL, NULL, NULL, 'E330, citric acid', 'To be debated. Made from mold,
        not from lemons.', ' Food additives ', ' Additives '),
       (1, NULL, NULL, NULL, NULL, ' E331, sodium citrate', 'Often well tolerated.', 'Food additives', 'Additives'),
       (1, NULL, NULL, NULL, NULL, 'E332, potassium citrate', 'Often well tolerated.', 'Food additives', 'Additives'),
       (1, NULL, NULL, NULL, NULL, 'E333, calcium citrate', 'Often well tolerated.', 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E334, tartaric acid', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E335, sodium tartrate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E336, cream of tartar', NULL, 'Food additives', 'Additives'),
       (1, NULL, NULL, NULL, NULL, 'E340, potassium phosphates', NULL, 'Food additives', 'Additives'),
       (1, NULL, NULL, NULL, NULL, 'E380, ammonium citrate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E400, alginic acid', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E401, sodium alginate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E402, potassium alginate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E403, ammonium alginate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E404, calcium alginate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E405, propylene glycolic alginate', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'E406, agar', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E407, carrageenan', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E410, locust bean gum',
        'Thickening agent and gelling agent, extracted from the seeds of the carob tree.', 'Food additives',
        'Additives'),
       (1, 'L', NULL, NULL, NULL, 'E412, guar gum', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E413, tragacanth', NULL, 'Food additives', 'Additives'),
       (1, 'L', NULL, NULL, NULL, 'E414, gum arabic', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E415, xanthan gum', NULL, 'Food additives', 'Additives'),
       (1, 'L', NULL, NULL, NULL, 'E416, gum karaya', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E420, sorbitol', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E421, mannitol', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E422, glycerol', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E440, pectin', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'E441, gelatin', 'Controversial, may also be tolerated.', 'Food additives',
        'Additives'),
       (2, '?', NULL, NULL, NULL, 'E452, polyphosphates', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E460, cellulose', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E461, methyl cellulose', 'May produce laxative effects in large quantities.',
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E462, ethyl cellulose', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E463, hydroxypropylcellulose', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E464, hypromellose', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E465, ethyl methyl cellulose', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E500i, sodium carbonate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E500ii, sodium hydrogen carbonate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E501, potassium carbonate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E503, ammonium carbonate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E504, magnesium carbonate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E507, hydrochloric acid', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E579, iron(II) gluconate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E620, glutamic acid', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E621, monosodium glutamate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E622, potassium glutamate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E623, calcium diglutamate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E624, monoammonium glutamate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E625, magnesium diglutamate', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E626, guanosine monophosphate, 5 - guanidylic acid, guanylic acid', NULL, 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E650, zinc acetate', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'E900, polydimethylsiloxane, PDMS, dimethicone, dimethylpolysiloxane', NULL,
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E901, beeswax', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E955, sucralose', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'E960, steviol glycosides', NULL, 'Food additives', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'erythrosine, E127', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'ethyl cellulose, E462', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'ethyl methyl cellulose, E465', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'ethylparaben, ethyl para-hydroxybenzoate, E214, E215', NULL, 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'ferrous gluconate, iron(II) gluconate, E579', NULL, 'Food additives', 'Additives'),
       (1, 'L', NULL, NULL, NULL, 'fizzy drinks', 'Only short time effects. Symptoms quickly disappear',
        'Food additives', 'Additives'),
       (1, 'L', NULL, NULL, NULL, 'flavin mononucleotide, E101a', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'flavour enhancers, glutamates, E620 - 625 ', NULL, 'Food additives', 'Additives'),
       (1, NULL, NULL, NULL, NULL, 'flavourings, flavorings', 'This can be anything. Mostly not well tolerated.',
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'gamma-tocopherol, vitamin E, E308', NULL, 'Food additives', 'Additives'),
       (1, '?', '?', NULL, NULL, 'gelatin, E441', 'Controversial, may also be tolerated.', 'Food additives',
        'Additives'),
       (2, 'L', NULL, NULL, NULL, 'glutamates, glutamic acid and its salts, E620 - 625 ', NULL, 'Food additives',
        'Additives'),
       (2, 'L', NULL, NULL, NULL, 'glutamic acid magnesium salt, E625', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'glutamic acid monosodium salt, E621', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'glutamic acid, E620', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'glycerol, E422', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'gold, E175', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'indigo carmine, E132', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'invertase, E1103', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'iron oxides, E172', NULL, 'Food additives', 'Additives'),
       (1, 'L', NULL, NULL, NULL, 'karaya gum, E416', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'lactic acid, E270', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'lecithins, E322', 'Mostly soya lecithin', 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'Lithol Rubine BK, E180', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'locust bean gum, E410',
        'Thickening agent and gelling agent, extracted from the seeds of the carob tree.', 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'magnesium carbonate, E504', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'magnesium diglutamate, E625', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'malic acid, E296', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'mannitol, E421', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'methyl cellulose, E461', 'May produce laxative effects in large quantities.',
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'methyl ethyl cellulose, E465', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'methylparaben, E218, E219', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'monoammonium glutamate, E624', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'monosodium ascorbate, E301', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'monosodium glutamate, E621', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'natamycin, E235', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'nisin, E234', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'norbixin, E160b', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'octyl gallate, E311', NULL, 'Food additives', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'orange yellow S, E110', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'orthophenyl phenol, E231', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'parabens, E214 - 219 ', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'Patent blue V, E131', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'pectin, E440', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'plain caramel, E150a', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'polyvinylpolypyrrolidone, E1202', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'polyvinylpyrrolidone, E1201', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'ponceau 4R, E124', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'potassium acetate, E261', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'potassium alginate, E402', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'potassium benzoate, E212', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'potassium bitartrate, E336', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'potassium carbonate, E501', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'potassium citrate, E332', 'Often well tolerated.', 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'potassium glutamate, E622', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'potassium hydrogen sulfite, E228', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'potassium hydrogen tartrate, E336', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'potassium lactate, E326', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'potassium metabisulfite, E224', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'potassium nitrite, E249', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'potassium polyphosphate, E452', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'potassium pyrosulfite, E224', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'potassium sorbate, E202', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'potassium sulfite, E225', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'povidone, E1201', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'propionic acid, E280', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'propyl gallate, E310', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'propylene glycolic alginate, E405', NULL, 'Food additives', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'quinoline yellow, E104', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'Red 2G, E128', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sodium acetate, E262', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sodium alginate, E401', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sodium ascorbate, E301', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sodium benzoate, E211', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sodium bisulphite, E222', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sodium carbonate, E500i', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'sodium citrate, E331', 'Often well tolerated.', 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sodium erythorbate, E316', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sodium hydrogen carbonate, E500ii', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sodium hydrogen sulphite, E222', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sodium lactate, E325', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sodium metabisulfite, E223', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sodium nitrate, E251', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sodium nitrite, E250', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sodium orthophenyl phenol, E232', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sodium polyphosphate, E452', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sodium pyrosulfite, E223', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sodium sulfite, E221', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sodium tartrate, E335', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sorbates, E200 - E203', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sorbic acid, E200', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'starch, amylum', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'steviol glycosides, E960', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sucralose, E955', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sulfites, E220 - E228', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sulfur dioxide, E220', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'sulphan blue, E131', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'sulphite ammonia caramel, E150d', 'Possibly not as good tolerated as E150?',
        'Food additives', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'sunset yellow FCF, E110', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'tartaric acid, E334', NULL, 'Food additives', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'tartrazine, E102', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'titanium dioxide, E171', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'tocopherol, E306', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'tragacanth, E413', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'triammonium citrate, E380', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'tricalcium phosphate, E340', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'tripotassium citrate, E332', 'Often well tolerated.', 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'tripotassium phosphate, E340', NULL, 'Food additives', 'Additives'),
       (1, '?', NULL, NULL, NULL, 'trisodium citrate, E331', 'Often well tolerated.', 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'vanillin (synthetic)', 'Slightly irritating. Use sparingly.', 'Food additives',
        'Additives'),
       (0, NULL, NULL, NULL, NULL, 'vitamin C, E300',
        'Lowers histamine levels, but is also a weak DAO inhibitor. Good for those with MCAS, bad for those with HIT?',
        'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'vitamin E, alpha - tocopherol, E307', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'vitamin E, delta - tocopherol, E309', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'vitamin E, gamma - tocopherol, E308', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'vitamin E, gamma - tocopherol, E308', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'vitamin E, tocopherol, E306', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'xanthan gum, E415', NULL, 'Food additives', 'Additives'),
       (0, NULL, NULL, NULL, NULL, 'zinc acetate, E650', NULL, 'Food additives', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'folic acid, vitamin B9',
        'To be debated. Other name: pteroyl-L-glutamic acid (similar to glutamic acid / glutamate?)',
        'Vitamins, dietary minerals, trace elements, stimulants', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'iodine', NULL, 'Vitamins, dietary minerals, trace elements, stimulants',
        'Additives'),
       (2, 'L', NULL, NULL, NULL, 'iodized table salt', NULL, 'Vitamins, dietary minerals, trace elements, stimulants',
        'Additives'),
       (3, 'L', NULL, NULL, NULL, 'potassium iodate', 'e.g. as additive in iodized table salt',
        'Vitamins, dietary minerals, trace elements, stimulants', 'Additives'),
       (3, 'L', NULL, NULL, NULL, 'potassium iodide', 'e.g. as additive in iodized table salt',
        'Vitamins, dietary minerals, trace elements, stimulants', 'Additives'),
       (2, 'B', NULL, NULL, NULL, 'theobromine', NULL, 'Vitamins, dietary minerals, trace elements, stimulants',
        'Additives'),
       (2, 'L', NULL, NULL, NULL, 'vitamin B9, folic acid, folate',
        'To be debated. Other name: pteroyl-L-glutamic acid (similar to glutamic acid / glutamate?)',
        'Vitamins, dietary minerals, trace elements, stimulants', 'Additives'),
       (2, 'B', NULL, NULL, NULL, 'xantheose, theobromine', NULL,
        'Vitamins, dietary minerals, trace elements, stimulants', 'Additives'),
       (2, 'L', NULL, NULL, NULL, 'liquorice', NULL, 'Preparations, mixtures', 'Additives'),
       (1, NULL, NULL, NULL, NULL, 'marzipan', 'Small amounts are well tolerated if without incompatible additives.',
        'Preparations, mixtures', 'Additives'),
       (1, NULL, NULL, NULL, NULL, 'marchpane', 'Small amounts are well tolerated if without incompatible additives.',
        'Preparations, mixtures', 'Additives'),
       (2, 'A', NULL, NULL, NULL, 'chocolate, brown / black', 'Tyramine, phenylethylamine', 'Preparations, mixtures',
        'Additives'),
       (1, '?', NULL, NULL, NULL, 'chocolate, white', 'Mostly well tolerated', 'Preparations, mixtures', 'Additives'),
       (2, 'H', 'L', NULL, NULL, 'mustard', 'Preparation (mixture) of mustard seeds, vinegar, etc.',
        ' Preparations, mixtures', 'Additives'),
       (2, NULL, NULL, NULL, NULL, 'tofu', NULL, 'Preparations, mixtures', 'Additives');