server:
  port: 8080

spring:
  application:
    name: "histamine-food-ms"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8888"

  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: never
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "histamine-food-ms"
    description: "Allergy Friendly Meals Application"
    version: "1.0.0"