spring:
  application:
    name: "histamine-food-ms"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8888"

  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: never
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081