services:
  mongodb:
    image: mongo:6.0.17
    container_name: ingr_mgmt-mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - data:/data

  mongo-express:
    image: mongo-express:1.0.2
    container_name: ingr_mgmt-mongo-exp 
    ports:
      - "8090:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb

# Define named volumes
volumes:
  data: {}

networks:
  default:
    name: ingr_mongodb_network